# Site settings
title: BigMao Radio Station
email: maojianwei2012@126.com
description: MaoJianwei
#markdown_ext: md,markdown,mkd,mkdn
#markdown: Kramdown
markdown: Redcarpet

# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
url: http://maojianwei.github.io/ # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: MaoJianwei
permalink: /:year/:month/:day/:title/
excerpt_separator: "\n\n\n"
# Build settings
#markdown: kramdown
baseurl: /
# highlight
# 本地用rouge, github上用pygments
highlighter: pygments

timezone: Asia/Beijing


# highlighter: rouge
# highlighter: false