# Site settings
title: BigMao Radio Station
maoHeader: SDN / NFV Learner
email: MaoJianwei2012@126.com
description: Jianwei Mao
myName: 毛健炜
BUPTname: 北京邮电大学
chinaName: China
Resume: 毛健炜，2016/09-至今，研究生，未来网络理论与应用实验室(FNLab)，北京邮电大学信息与通信工程学院。
myPhoto: http://www.maojianwei.win/resources/picture/index/Myphoto.jpg

#https://avatars3.githubusercontent.com/u/12800168?v=3&amp;s=460

#markdown_ext: md,markdown,mkd,mkdn
#markdown: Kramdown
# markdown: Redcarpet

# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
url: http://www.maojianwei.win # the base hostname & protocol for your site, backup maojianwei.github.io
# twitter_username: jekyllrb
github_username: MaoJianwei
permalink: /:year/:month/:day/:title/
excerpt_separator: "\n\n\n"

timezone: Asia/Shanghai
highlighter: rouge
# highlighter: false
gems:
  - jekyll-sitemap
