# Site settings
title: BigMao Radio Station
email: MaoJianwei2012@126.com
description: MaoJianwei
myName: 毛健炜
BUPTname: 北京邮电大学
chinaName: China
Resume: 毛健炜，2016/09-至今，研究生，未来网络理论与应用实验室(FNLab)，北京邮电大学信息与通信工程学院。

#markdown_ext: md,markdown,mkd,mkdn
#markdown: Kramdown
# markdown: Redcarpet

# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
url: http://maojianwei.github.io # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: MaoJianwei
permalink: /:year/:month/:day/:title/
excerpt_separator: "\n\n\n"

timezone: Asia/Beijing
highlighter: rouge
# highlighter: false
gems:
  - jekyll-sitemap
